development:
  battle_net_api_key: "zkknhcmzz834sge3uvathm9q6u88vnbt"
  battle_net_secret_key: "cdzvXUrW86qD29FvkygrjvzyFEGyq4aS"
  gmail_email: "gwyattkelsey.dev@gmail.com"
  gmail_password: "tfmOmlAI.19!)g"

production:
  battle_net_api_key: "zkknhcmzz834sge3uvathm9q6u88vnbt"
  battle_net_secret_key: "cdzvXUrW86qD29FvkygrjvzyFEGyq4aS"