defaults: &defaults
  cutoff:
    attendance: 15
    delinquent: 30
    tardy: 60
  guild:
    name: 'Vox Immortalis'
    realm: 'Hyjal'
    region: 'us'
  raid:
    start_time: '6:30 PM'
    end_time:   '10:30 PM'
    size: 20
  roster:
    size: 25
  standing:
    attendance_gain: 100.0
    delinquent_loss: -100.0
    unexcused_absence_loss: -50.0

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults